// Comprehensive mock parts data for all categories
// Based on real UK aftermarket parts for Ford Focus Mk4 (2018+)

export const MOCK_PARTS = {
  'air-filters': [
    { articleId: 1001, articleNumber: 'F 026 400 672', supplierName: 'Bosch', productName: 'Air Filter' },
    { articleId: 1002, articleNumber: 'C 27 031', supplierName: 'MANN-FILTER', productName: 'Air Filter' },
    { articleId: 1003, articleNumber: 'LX 4849', supplierName: 'MAHLE', productName: 'Air Filter' },
    { articleId: 1004, articleNumber: '33-3131', supplierName: 'K&N Filters', productName: 'Performance Air Filter' },
    { articleId: 1005, articleNumber: 'CA12617', supplierName: 'FRAM', productName: 'Air Filter' },
    { articleId: 1006, articleNumber: 'CAF101189P', supplierName: 'Champion', productName: 'Air Filter' },
    { articleId: 1007, articleNumber: 'E1628L', supplierName: 'Hengst Filter', productName: 'Air Filter' },
    { articleId: 1008, articleNumber: 'WA9878', supplierName: 'WIX Filters', productName: 'Air Filter' },
    { articleId: 1009, articleNumber: 'PP2008', supplierName: 'Pipercross', productName: 'Performance Air Filter' },
    { articleId: 1010, articleNumber: 'NFA1416', supplierName: 'NAPA', productName: 'Air Filter' },
    { articleId: 1011, articleNumber: '109102', supplierName: 'Febi Bilstein', productName: 'Air Filter' },
    { articleId: 1012, articleNumber: 'ADF122238', supplierName: 'Blue Print', productName: 'Air Filter' },
  ],
  'oil-filters': [
    { articleId: 2001, articleNumber: 'F 026 407 213', supplierName: 'Bosch', productName: 'Oil Filter' },
    { articleId: 2002, articleNumber: 'W 712/94', supplierName: 'MANN-FILTER', productName: 'Oil Filter' },
    { articleId: 2003, articleNumber: 'OC 1480', supplierName: 'MAHLE', productName: 'Oil Filter' },
    { articleId: 2004, articleNumber: 'LS993', supplierName: 'PURFLUX', productName: 'Oil Filter' },
    { articleId: 2005, articleNumber: 'COF100698S', supplierName: 'Champion', productName: 'Oil Filter' },
    { articleId: 2006, articleNumber: 'PH12080', supplierName: 'FRAM', productName: 'Oil Filter' },
    { articleId: 2007, articleNumber: 'WL7516', supplierName: 'WIX Filters', productName: 'Oil Filter' },
    { articleId: 2008, articleNumber: '109214', supplierName: 'Febi Bilstein', productName: 'Oil Filter' },
    { articleId: 2009, articleNumber: 'ADM52117', supplierName: 'Blue Print', productName: 'Oil Filter' },
  ],
  'fuel-filters': [
    { articleId: 3001, articleNumber: 'F 026 402 846', supplierName: 'Bosch', productName: 'Fuel Filter' },
    { articleId: 3002, articleNumber: 'WK 69/2', supplierName: 'MANN-FILTER', productName: 'Fuel Filter' },
    { articleId: 3003, articleNumber: 'KL 756', supplierName: 'MAHLE', productName: 'Fuel Filter' },
    { articleId: 3004, articleNumber: 'FCS811', supplierName: 'PURFLUX', productName: 'Fuel Filter' },
    { articleId: 3005, articleNumber: 'WF8510', supplierName: 'WIX Filters', productName: 'Fuel Filter' },
    { articleId: 3006, articleNumber: 'CFF100661', supplierName: 'Champion', productName: 'Fuel Filter' },
    { articleId: 3007, articleNumber: 'ADM52352', supplierName: 'Blue Print', productName: 'Fuel Filter' },
  ],
  'cabin-filters': [
    { articleId: 4001, articleNumber: '1 987 435 005', supplierName: 'Bosch', productName: 'Cabin Filter' },
    { articleId: 4002, articleNumber: 'CUK 25 007', supplierName: 'MANN-FILTER', productName: 'Cabin Filter (Activated Carbon)' },
    { articleId: 4003, articleNumber: 'LAK 875', supplierName: 'MAHLE', productName: 'Cabin Filter (Activated Carbon)' },
    { articleId: 4004, articleNumber: 'AH399', supplierName: 'PURFLUX', productName: 'Cabin Filter' },
    { articleId: 4005, articleNumber: 'WP2155', supplierName: 'WIX Filters', productName: 'Cabin Filter' },
    { articleId: 4006, articleNumber: 'CCF0324', supplierName: 'Champion', productName: 'Cabin Filter' },
    { articleId: 4007, articleNumber: 'ADM52561', supplierName: 'Blue Print', productName: 'Cabin Filter' },
    { articleId: 4008, articleNumber: '40529', supplierName: 'Febi Bilstein', productName: 'Cabin Filter' },
  ],
  'spark-plugs': [
    { articleId: 5001, articleNumber: 'FR7NE2', supplierName: 'Bosch', productName: 'Spark Plug' },
    { articleId: 5002, articleNumber: 'ILTR6A-8G', supplierName: 'NGK', productName: 'Spark Plug (Iridium)' },
    { articleId: 5003, articleNumber: 'ITV22', supplierName: 'Denso', productName: 'Spark Plug (Iridium TT)' },
    { articleId: 5004, articleNumber: 'RE8PMC', supplierName: 'Champion', productName: 'Spark Plug' },
    { articleId: 5005, articleNumber: 'OE249', supplierName: 'Champion', productName: 'Spark Plug (OE Spec)' },
    { articleId: 5006, articleNumber: 'ZR6SPP3320', supplierName: 'Bosch', productName: 'Spark Plug (Platinum)' },
  ],
  'glow-plugs': [
    { articleId: 5101, articleNumber: 'GLP223', supplierName: 'Bosch', productName: 'Glow Plug' },
    { articleId: 5102, articleNumber: 'DG-004', supplierName: 'Denso', productName: 'Glow Plug' },
    { articleId: 5103, articleNumber: 'CH265', supplierName: 'Champion', productName: 'Glow Plug' },
    { articleId: 5104, articleNumber: 'Y1002AS', supplierName: 'NGK', productName: 'Glow Plug' },
    { articleId: 5105, articleNumber: '11723', supplierName: 'Febi Bilstein', productName: 'Glow Plug' },
  ],
  'brake-pads': [
    { articleId: 6001, articleNumber: '0 986 494 664', supplierName: 'Bosch', productName: 'Brake Pad Set, Front' },
    { articleId: 6002, articleNumber: 'FDB4642', supplierName: 'Ferodo', productName: 'Brake Pad Set, Front' },
    { articleId: 6003, articleNumber: 'GDB2117', supplierName: 'TRW', productName: 'Brake Pad Set, Front' },
    { articleId: 6004, articleNumber: 'P 61 120', supplierName: 'Brembo', productName: 'Brake Pad Set, Front' },
    { articleId: 6005, articleNumber: 'MDB3926', supplierName: 'Mintex', productName: 'Brake Pad Set, Front' },
    { articleId: 6006, articleNumber: 'T2057', supplierName: 'Pagid', productName: 'Brake Pad Set, Front' },
    { articleId: 6007, articleNumber: 'DP2201', supplierName: 'EBC', productName: 'GreenStuff Brake Pad Set, Front' },
    { articleId: 6008, articleNumber: 'LP3226', supplierName: 'Delphi', productName: 'Brake Pad Set, Front' },
    { articleId: 6009, articleNumber: '117421', supplierName: 'Febi Bilstein', productName: 'Brake Pad Set, Front' },
    { articleId: 6010, articleNumber: 'ADM54290', supplierName: 'Blue Print', productName: 'Brake Pad Set, Front' },
    { articleId: 6011, articleNumber: '0 986 495 172', supplierName: 'Bosch', productName: 'Brake Pad Set, Rear' },
    { articleId: 6012, articleNumber: 'FDB4643', supplierName: 'Ferodo', productName: 'Brake Pad Set, Rear' },
  ],
  'brake-discs': [
    { articleId: 7001, articleNumber: '0 986 479 D98', supplierName: 'Bosch', productName: 'Brake Disc, Front' },
    { articleId: 7002, articleNumber: 'DF6680', supplierName: 'TRW', productName: 'Brake Disc, Front' },
    { articleId: 7003, articleNumber: '09.C881.11', supplierName: 'Brembo', productName: 'Brake Disc, Front (Vented)' },
    { articleId: 7004, articleNumber: 'MDC3266', supplierName: 'Mintex', productName: 'Brake Disc, Front' },
    { articleId: 7005, articleNumber: '100.3372.70', supplierName: 'Zimmermann', productName: 'Brake Disc, Front (Sport)' },
    { articleId: 7006, articleNumber: 'BG4699C', supplierName: 'Delphi', productName: 'Brake Disc, Front' },
    { articleId: 7007, articleNumber: 'ADM54397', supplierName: 'Blue Print', productName: 'Brake Disc, Front' },
    { articleId: 7008, articleNumber: '09.C882.10', supplierName: 'Brembo', productName: 'Brake Disc, Rear (Solid)' },
    { articleId: 7009, articleNumber: 'DF6681', supplierName: 'TRW', productName: 'Brake Disc, Rear' },
  ],
  'brake-drums': [
    { articleId: 7101, articleNumber: 'DB4435', supplierName: 'TRW', productName: 'Brake Drum, Rear' },
    { articleId: 7102, articleNumber: '14.B135.10', supplierName: 'Brembo', productName: 'Brake Drum, Rear' },
    { articleId: 7103, articleNumber: 'BF635', supplierName: 'Delphi', productName: 'Brake Drum, Rear' },
    { articleId: 7104, articleNumber: 'ADM54439', supplierName: 'Blue Print', productName: 'Brake Drum, Rear' },
  ],
  'brake-shoes': [
    { articleId: 7201, articleNumber: 'GS8801', supplierName: 'TRW', productName: 'Brake Shoe Set, Rear' },
    { articleId: 7202, articleNumber: 'FSB4158', supplierName: 'Ferodo', productName: 'Brake Shoe Set, Rear' },
    { articleId: 7203, articleNumber: 'MSP458', supplierName: 'Mintex', productName: 'Brake Shoe Set, Rear' },
    { articleId: 7204, articleNumber: 'LS2121', supplierName: 'Delphi', productName: 'Brake Shoe Set, Rear' },
  ],
  'brake-hoses': [
    { articleId: 7301, articleNumber: 'PHD901', supplierName: 'TRW', productName: 'Brake Hose, Front' },
    { articleId: 7302, articleNumber: 'LH7358', supplierName: 'Delphi', productName: 'Brake Hose, Front' },
    { articleId: 7303, articleNumber: 'ADM55350', supplierName: 'Blue Print', productName: 'Brake Hose, Front' },
    { articleId: 7304, articleNumber: 'PHD902', supplierName: 'TRW', productName: 'Brake Hose, Rear' },
  ],
  'brake-calipers': [
    { articleId: 7401, articleNumber: 'BHQ974E', supplierName: 'TRW', productName: 'Brake Caliper, Front Left' },
    { articleId: 7402, articleNumber: 'BHQ975E', supplierName: 'TRW', productName: 'Brake Caliper, Front Right' },
    { articleId: 7403, articleNumber: 'LC7510', supplierName: 'Delphi', productName: 'Brake Caliper, Front Left' },
    { articleId: 7404, articleNumber: 'LC7511', supplierName: 'Delphi', productName: 'Brake Caliper, Front Right' },
  ],
  'timing-belts': [
    { articleId: 8001, articleNumber: 'CT1177', supplierName: 'Continental', productName: 'Timing Belt' },
    { articleId: 8002, articleNumber: 'K015671XS', supplierName: 'Gates', productName: 'Timing Belt Kit' },
    { articleId: 8003, articleNumber: '530 0697 10', supplierName: 'INA', productName: 'Timing Belt Kit (with Water Pump)' },
    { articleId: 8004, articleNumber: '1 987 946 567', supplierName: 'Bosch', productName: 'Timing Belt Kit' },
    { articleId: 8005, articleNumber: 'DKB-8006', supplierName: 'Dayco', productName: 'Timing Belt Kit' },
  ],
  'drive-belts': [
    { articleId: 8101, articleNumber: '6PK1680', supplierName: 'Continental', productName: 'V-Ribbed Belt' },
    { articleId: 8102, articleNumber: '6PK1680SF', supplierName: 'Gates', productName: 'Micro-V Belt' },
    { articleId: 8103, articleNumber: '1 987 948 518', supplierName: 'Bosch', productName: 'V-Ribbed Belt' },
    { articleId: 8104, articleNumber: '6PK1680', supplierName: 'Dayco', productName: 'V-Ribbed Belt' },
    { articleId: 8105, articleNumber: 'VKM 31100', supplierName: 'SKF', productName: 'Belt Tensioner' },
  ],
  'gaskets-seals': [
    { articleId: 8201, articleNumber: '431.090', supplierName: 'ELRING', productName: 'Gasket, Cylinder Head Cover' },
    { articleId: 8202, articleNumber: '580.810', supplierName: 'ELRING', productName: 'Gasket, Oil Sump' },
    { articleId: 8203, articleNumber: 'OS32356', supplierName: 'Victor Reinz', productName: 'Crankshaft Oil Seal' },
    { articleId: 8204, articleNumber: '713630710', supplierName: 'Victor Reinz', productName: 'Gasket, Cylinder Head' },
    { articleId: 8205, articleNumber: '23820', supplierName: 'Febi Bilstein', productName: 'Valve Cover Gasket' },
  ],
  'engine-mounts': [
    { articleId: 8301, articleNumber: 'TEM129', supplierName: 'Corteco', productName: 'Engine Mount, Right' },
    { articleId: 8302, articleNumber: 'TEM130', supplierName: 'Corteco', productName: 'Engine Mount, Left' },
    { articleId: 8303, articleNumber: '37620', supplierName: 'Febi Bilstein', productName: 'Engine Mount, Right' },
    { articleId: 8304, articleNumber: '37621', supplierName: 'Febi Bilstein', productName: 'Engine Mount, Left' },
    { articleId: 8305, articleNumber: 'ADM58090', supplierName: 'Blue Print', productName: 'Engine Mount, Rear (Lower)' },
  ],
  'turbo-parts': [
    { articleId: 8401, articleNumber: '54399880027', supplierName: 'BorgWarner', productName: 'Turbocharger' },
    { articleId: 8402, articleNumber: '782404-5001S', supplierName: 'Garrett', productName: 'Turbocharger' },
    { articleId: 8403, articleNumber: '454229-0001', supplierName: 'Garrett', productName: 'Turbo Core Assembly' },
    { articleId: 8404, articleNumber: '04-16043-01', supplierName: 'ELRING', productName: 'Turbo Gasket Kit' },
  ],
  'shock-absorbers': [
    { articleId: 9001, articleNumber: '334 838', supplierName: 'KYB', productName: 'Shock Absorber, Front' },
    { articleId: 9002, articleNumber: 'G8206', supplierName: 'Monroe', productName: 'Shock Absorber, Front' },
    { articleId: 9003, articleNumber: '22-259950', supplierName: 'Bilstein', productName: 'Shock Absorber, Front (B4)' },
    { articleId: 9004, articleNumber: 'JGM1263T', supplierName: 'TRW', productName: 'Shock Absorber, Front' },
    { articleId: 9005, articleNumber: '344 839', supplierName: 'KYB', productName: 'Shock Absorber, Rear' },
    { articleId: 9006, articleNumber: 'G1099', supplierName: 'Monroe', productName: 'Shock Absorber, Rear' },
    { articleId: 9007, articleNumber: '19-259956', supplierName: 'Bilstein', productName: 'Shock Absorber, Rear (B4)' },
    { articleId: 9008, articleNumber: 'JGT1274T', supplierName: 'TRW', productName: 'Shock Absorber, Rear' },
    { articleId: 9009, articleNumber: '37312', supplierName: 'Febi Bilstein', productName: 'Shock Absorber, Front' },
  ],
  'coil-springs': [
    { articleId: 9101, articleNumber: 'RI6498', supplierName: 'KYB', productName: 'Coil Spring, Front' },
    { articleId: 9102, articleNumber: 'SP3881', supplierName: 'Monroe', productName: 'Coil Spring, Front' },
    { articleId: 9103, articleNumber: 'JCS2122T', supplierName: 'TRW', productName: 'Coil Spring, Front' },
    { articleId: 9104, articleNumber: 'RG6503', supplierName: 'KYB', productName: 'Coil Spring, Rear' },
    { articleId: 9105, articleNumber: 'SP3882', supplierName: 'Monroe', productName: 'Coil Spring, Rear' },
  ],
  'suspension-arms': [
    { articleId: 9201, articleNumber: 'JTC2336', supplierName: 'TRW', productName: 'Wishbone, Front Lower Left' },
    { articleId: 9202, articleNumber: 'JTC2337', supplierName: 'TRW', productName: 'Wishbone, Front Lower Right' },
    { articleId: 9203, articleNumber: 'FCA7549', supplierName: 'First Line', productName: 'Wishbone, Front Lower Left' },
    { articleId: 9204, articleNumber: 'FCA7550', supplierName: 'First Line', productName: 'Wishbone, Front Lower Right' },
    { articleId: 9205, articleNumber: '39088', supplierName: 'Febi Bilstein', productName: 'Wishbone, Front Lower' },
    { articleId: 9206, articleNumber: 'ADM58628', supplierName: 'Blue Print', productName: 'Wishbone, Front Lower' },
  ],
  'tie-rod-ends': [
    { articleId: 9301, articleNumber: 'JTE1239', supplierName: 'TRW', productName: 'Tie Rod End, Front' },
    { articleId: 9302, articleNumber: 'TA3490', supplierName: 'Delphi', productName: 'Tie Rod End, Front' },
    { articleId: 9303, articleNumber: 'FTR5964', supplierName: 'First Line', productName: 'Tie Rod End, Front' },
    { articleId: 9304, articleNumber: 'ADM58735', supplierName: 'Blue Print', productName: 'Tie Rod End, Front' },
    { articleId: 9305, articleNumber: '44102', supplierName: 'Febi Bilstein', productName: 'Tie Rod End, Front' },
  ],
  'wheel-bearings': [
    { articleId: 9401, articleNumber: 'VKBA 6985', supplierName: 'SKF', productName: 'Wheel Bearing Kit, Front' },
    { articleId: 9402, articleNumber: 'R140.88', supplierName: 'SNR', productName: 'Wheel Bearing Kit, Front' },
    { articleId: 9403, articleNumber: 'ADM58238', supplierName: 'Blue Print', productName: 'Wheel Bearing Kit, Front' },
    { articleId: 9404, articleNumber: '38740', supplierName: 'Febi Bilstein', productName: 'Wheel Bearing Kit, Front' },
    { articleId: 9405, articleNumber: 'VKBA 6986', supplierName: 'SKF', productName: 'Wheel Bearing Kit, Rear' },
  ],
  'anti-roll-bar-links': [
    { articleId: 9501, articleNumber: 'JTS826', supplierName: 'TRW', productName: 'Anti-Roll Bar Link, Front' },
    { articleId: 9502, articleNumber: 'FDL7599', supplierName: 'First Line', productName: 'Anti-Roll Bar Link, Front' },
    { articleId: 9503, articleNumber: 'TC3413', supplierName: 'Delphi', productName: 'Anti-Roll Bar Link, Front' },
    { articleId: 9504, articleNumber: 'ADM58552', supplierName: 'Blue Print', productName: 'Anti-Roll Bar Link, Front' },
    { articleId: 9505, articleNumber: '38122', supplierName: 'Febi Bilstein', productName: 'Anti-Roll Bar Link, Front' },
  ],
  'batteries': [
    { articleId: 10001, articleNumber: 'S4 008', supplierName: 'Bosch', productName: 'Car Battery 74Ah 680A' },
    { articleId: 10002, articleNumber: 'YBX3096', supplierName: 'Yuasa', productName: 'Car Battery 76Ah 680A' },
    { articleId: 10003, articleNumber: 'EB740', supplierName: 'Exide', productName: 'Car Battery 74Ah 680A' },
    { articleId: 10004, articleNumber: 'HB096', supplierName: 'Varta', productName: 'Blue Dynamic 74Ah 680A' },
    { articleId: 10005, articleNumber: '096', supplierName: 'Lion', productName: 'Car Battery 74Ah 680A' },
  ],
  'alternators': [
    { articleId: 10101, articleNumber: '1 986 A01 515', supplierName: 'Bosch', productName: 'Alternator 14V 150A' },
    { articleId: 10102, articleNumber: 'DRA0133', supplierName: 'Denso', productName: 'Alternator 14V 150A' },
    { articleId: 10103, articleNumber: 'TG15C183', supplierName: 'Valeo', productName: 'Alternator 14V 150A' },
    { articleId: 10104, articleNumber: 'DAN1131', supplierName: 'Delphi', productName: 'Alternator 14V 150A' },
  ],
  'starter-motors': [
    { articleId: 10201, articleNumber: '0 001 138 080', supplierName: 'Bosch', productName: 'Starter Motor 1.4kW' },
    { articleId: 10202, articleNumber: 'DSN1260', supplierName: 'Denso', productName: 'Starter Motor 1.4kW' },
    { articleId: 10203, articleNumber: 'TS22E15', supplierName: 'Valeo', productName: 'Starter Motor 1.4kW' },
    { articleId: 10204, articleNumber: 'DRS0889', supplierName: 'Delphi', productName: 'Starter Motor 1.4kW' },
  ],
  'bulbs': [
    { articleId: 10301, articleNumber: '1 987 301 013', supplierName: 'Bosch', productName: 'Headlight Bulb H7 55W' },
    { articleId: 10302, articleNumber: '64210', supplierName: 'Osram', productName: 'Original Halogen H7 55W' },
    { articleId: 10303, articleNumber: '12972PRC1', supplierName: 'Philips', productName: 'Vision H7 55W' },
    { articleId: 10304, articleNumber: '64210NBU', supplierName: 'Osram', productName: 'Night Breaker Unlimited H7' },
    { articleId: 10305, articleNumber: '12972WHVSM', supplierName: 'Philips', productName: 'WhiteVision ultra H7' },
    { articleId: 10306, articleNumber: '64210NL', supplierName: 'Osram', productName: 'Night Breaker Laser H7' },
  ],
  'sensors': [
    { articleId: 10401, articleNumber: '0 261 210 433', supplierName: 'Bosch', productName: 'Crankshaft Position Sensor' },
    { articleId: 10402, articleNumber: '0 281 002 801', supplierName: 'Bosch', productName: 'MAP Sensor' },
    { articleId: 10403, articleNumber: '0 258 010 416', supplierName: 'Bosch', productName: 'Lambda Sensor (Pre-Cat)' },
    { articleId: 10404, articleNumber: 'SS11206', supplierName: 'Delphi', productName: 'ABS Speed Sensor, Front' },
    { articleId: 10405, articleNumber: '44758', supplierName: 'Febi Bilstein', productName: 'Coolant Temperature Sensor' },
    { articleId: 10406, articleNumber: 'ADM57230', supplierName: 'Blue Print', productName: 'Camshaft Position Sensor' },
  ],
  'ignition-coils': [
    { articleId: 10501, articleNumber: '0 221 504 703', supplierName: 'Bosch', productName: 'Ignition Coil' },
    { articleId: 10502, articleNumber: 'DIC0109', supplierName: 'Denso', productName: 'Ignition Coil' },
    { articleId: 10503, articleNumber: '245728', supplierName: 'Valeo', productName: 'Ignition Coil' },
    { articleId: 10504, articleNumber: 'GN10791-12B1', supplierName: 'Delphi', productName: 'Ignition Coil' },
    { articleId: 10505, articleNumber: '48348', supplierName: 'NGK', productName: 'Ignition Coil' },
  ],
  'radiators': [
    { articleId: 11001, articleNumber: 'RA528001', supplierName: 'Nissens', productName: 'Radiator, Engine Cooling' },
    { articleId: 11002, articleNumber: 'DRM10144', supplierName: 'Denso', productName: 'Radiator, Engine Cooling' },
    { articleId: 11003, articleNumber: '734741', supplierName: 'Valeo', productName: 'Radiator, Engine Cooling' },
    { articleId: 11004, articleNumber: 'VWA2335', supplierName: 'NRF', productName: 'Radiator, Engine Cooling' },
  ],
  'thermostats': [
    { articleId: 11101, articleNumber: 'TX 197 88D', supplierName: 'Mahle', productName: 'Thermostat' },
    { articleId: 11102, articleNumber: 'TH44788G1', supplierName: 'Gates', productName: 'Thermostat' },
    { articleId: 11103, articleNumber: '18770', supplierName: 'Febi Bilstein', productName: 'Thermostat' },
    { articleId: 11104, articleNumber: 'ADM59234', supplierName: 'Blue Print', productName: 'Thermostat' },
  ],
  'water-pumps': [
    { articleId: 11201, articleNumber: 'PA 1555', supplierName: 'Graf', productName: 'Water Pump' },
    { articleId: 11202, articleNumber: 'FWP2285', supplierName: 'First Line', productName: 'Water Pump' },
    { articleId: 11203, articleNumber: '506 0972 10', supplierName: 'INA', productName: 'Water Pump' },
    { articleId: 11204, articleNumber: 'ADM59152', supplierName: 'Blue Print', productName: 'Water Pump' },
    { articleId: 11205, articleNumber: '28821', supplierName: 'Febi Bilstein', productName: 'Water Pump' },
  ],
  'heater-parts': [
    { articleId: 11301, articleNumber: '73441', supplierName: 'Nissens', productName: 'Heater Radiator' },
    { articleId: 11302, articleNumber: '812499', supplierName: 'Valeo', productName: 'Heater Radiator' },
    { articleId: 11303, articleNumber: 'DRR10055', supplierName: 'Denso', productName: 'Heater Radiator' },
  ],
  'cooling-fans': [
    { articleId: 11401, articleNumber: '85712', supplierName: 'Nissens', productName: 'Radiator Fan (Electric)' },
    { articleId: 11402, articleNumber: '698750', supplierName: 'Valeo', productName: 'Radiator Fan (Electric)' },
    { articleId: 11403, articleNumber: 'DER10021', supplierName: 'Denso', productName: 'Radiator Fan' },
  ],
  'clutch-kits': [
    { articleId: 12001, articleNumber: '623 3595 00', supplierName: 'LuK', productName: 'Clutch Kit (3-piece)' },
    { articleId: 12002, articleNumber: '826 954', supplierName: 'Valeo', productName: 'Clutch Kit (3-piece)' },
    { articleId: 12003, articleNumber: '3000 951 429', supplierName: 'Sachs', productName: 'Clutch Kit (3-piece)' },
  ],
  'flywheels': [
    { articleId: 12101, articleNumber: '415 0577 10', supplierName: 'LuK', productName: 'Dual Mass Flywheel' },
    { articleId: 12102, articleNumber: '836 256', supplierName: 'Valeo', productName: 'Dual Mass Flywheel' },
    { articleId: 12103, articleNumber: '2294 002 130', supplierName: 'Sachs', productName: 'Dual Mass Flywheel' },
  ],
  'cv-joints': [
    { articleId: 12201, articleNumber: 'VKJP 01022', supplierName: 'SKF', productName: 'CV Boot Kit, Front' },
    { articleId: 12202, articleNumber: 'FCB6204', supplierName: 'First Line', productName: 'CV Boot Kit, Front' },
    { articleId: 12203, articleNumber: '100412', supplierName: 'GKN-Spidan', productName: 'CV Joint' },
    { articleId: 12204, articleNumber: 'ADM58989', supplierName: 'Blue Print', productName: 'CV Boot Kit' },
  ],
  'gearbox-mounts': [
    { articleId: 12301, articleNumber: '80004624', supplierName: 'Corteco', productName: 'Gearbox Mount' },
    { articleId: 12302, articleNumber: '37815', supplierName: 'Febi Bilstein', productName: 'Gearbox Mount' },
    { articleId: 12303, articleNumber: 'ADM58064', supplierName: 'Blue Print', productName: 'Gearbox Mount' },
  ],
  'wiper-blades': [
    { articleId: 13001, articleNumber: '3 397 118 979', supplierName: 'Bosch', productName: 'Wiper Blade Set, Flat (Aerotwin)' },
    { articleId: 13002, articleNumber: 'VM441', supplierName: 'Valeo', productName: 'Wiper Blade Set, Flat' },
    { articleId: 13003, articleNumber: 'DF-044', supplierName: 'Denso', productName: 'Wiper Blade Set, Flat' },
    { articleId: 13004, articleNumber: 'A 979 S', supplierName: 'Bosch', productName: 'Aerotwin Wiper Blade Set' },
    { articleId: 13005, articleNumber: 'H341', supplierName: 'Bosch', productName: 'Rear Wiper Blade' },
    { articleId: 13006, articleNumber: 'VR270', supplierName: 'Valeo', productName: 'Rear Wiper Blade' },
  ],
  'exhaust-parts': [
    { articleId: 13101, articleNumber: '256-812', supplierName: 'Bosal', productName: 'Exhaust Muffler, Rear' },
    { articleId: 13102, articleNumber: '39958', supplierName: 'Walker', productName: 'Exhaust Muffler, Rear' },
    { articleId: 13103, articleNumber: '256-040', supplierName: 'Bosal', productName: 'Exhaust Pipe' },
    { articleId: 13104, articleNumber: 'FP60064', supplierName: 'Klarius', productName: 'Exhaust Mounting Rubber' },
    { articleId: 13105, articleNumber: '105-165', supplierName: 'Bosal', productName: 'Exhaust Mounting Rubber' },
  ],
  'wing-mirrors': [
    { articleId: 13201, articleNumber: '338-0058', supplierName: 'TYC', productName: 'Mirror, Wing (Electric, Heated) Left' },
    { articleId: 13202, articleNumber: '338-0059', supplierName: 'TYC', productName: 'Mirror, Wing (Electric, Heated) Right' },
    { articleId: 13203, articleNumber: '6102-25-2001791P', supplierName: 'BLIC', productName: 'Mirror Glass, Left' },
    { articleId: 13204, articleNumber: '6102-25-2001792P', supplierName: 'BLIC', productName: 'Mirror Glass, Right' },
  ],
  'headlights': [
    { articleId: 13301, articleNumber: '20-16799-06-2', supplierName: 'TYC', productName: 'Headlight, Left' },
    { articleId: 13302, articleNumber: '20-16799-06-9', supplierName: 'TYC', productName: 'Headlight, Right' },
    { articleId: 13303, articleNumber: '1EL 011 738-311', supplierName: 'Hella', productName: 'Headlight, Left (LED)' },
    { articleId: 13304, articleNumber: '1EL 011 738-321', supplierName: 'Hella', productName: 'Headlight, Right (LED)' },
  ],
};

// Brand tier classification for price estimation
export const BRAND_TIERS = {
  premium: ['K&N Filters', 'Pipercross', 'Brembo', 'EBC', 'NGK', 'Denso', 'Bilstein', 'Sachs', 'Zimmermann', 'Osram', 'Philips', 'BorgWarner', 'Garrett', 'Hella'],
  oem: ['Bosch', 'MANN-FILTER', 'MAHLE', 'Hengst Filter', 'TRW', 'ATE', 'Valeo', 'LuK', 'Continental', 'Gates', 'INA', 'SKF', 'Nissens', 'NRF', 'GKN-Spidan', 'Victor Reinz', 'ELRING'],
  mid: ['FRAM', 'Champion', 'WIX Filters', 'Ferodo', 'Delphi', 'Mintex', 'Pagid', 'Monroe', 'KYB', 'SNR', 'Graf', 'Corteco', 'PURFLUX', 'Dayco', 'Walker', 'Bosal', 'Klarius', 'TYC'],
  budget: ['NAPA', 'Febi Bilstein', 'Blue Print', 'Comline', 'First Line', 'Apec', 'Lion', 'BLIC'],
};

// Base price ranges by category (GBP) [min, max] per tier
export const CATEGORY_PRICES = {
  'air-filters':          { budget: [6, 12],   mid: [10, 18],   oem: [14, 25],   premium: [25, 55] },
  'oil-filters':          { budget: [4, 8],    mid: [6, 12],    oem: [8, 16],    premium: [14, 28] },
  'fuel-filters':         { budget: [8, 14],   mid: [12, 22],   oem: [16, 30],   premium: [25, 45] },
  'cabin-filters':        { budget: [6, 12],   mid: [10, 18],   oem: [14, 28],   premium: [22, 40] },
  'spark-plugs':          { budget: [2, 5],    mid: [4, 8],     oem: [6, 12],    premium: [10, 22] },
  'glow-plugs':           { budget: [6, 12],   mid: [10, 18],   oem: [14, 25],   premium: [20, 35] },
  'brake-pads':           { budget: [15, 25],  mid: [22, 38],   oem: [30, 55],   premium: [45, 95] },
  'brake-discs':          { budget: [20, 35],  mid: [30, 55],   oem: [40, 75],   premium: [60, 140] },
  'brake-drums':          { budget: [18, 28],  mid: [25, 40],   oem: [32, 55],   premium: [45, 75] },
  'brake-shoes':          { budget: [12, 20],  mid: [18, 30],   oem: [25, 42],   premium: [35, 55] },
  'brake-hoses':          { budget: [6, 12],   mid: [10, 18],   oem: [14, 25],   premium: [20, 35] },
  'brake-calipers':       { budget: [40, 65],  mid: [55, 90],   oem: [75, 130],  premium: [100, 180] },
  'timing-belts':         { budget: [25, 50],  mid: [45, 85],   oem: [70, 140],  premium: [120, 220] },
  'drive-belts':          { budget: [8, 15],   mid: [12, 22],   oem: [18, 35],   premium: [28, 50] },
  'gaskets-seals':        { budget: [4, 12],   mid: [8, 22],    oem: [15, 35],   premium: [25, 55] },
  'engine-mounts':        { budget: [18, 30],  mid: [25, 45],   oem: [35, 65],   premium: [55, 95] },
  'turbo-parts':          { budget: [150, 300], mid: [250, 500], oem: [400, 800], premium: [600, 1200] },
  'shock-absorbers':      { budget: [25, 45],  mid: [35, 65],   oem: [50, 95],   premium: [80, 160] },
  'coil-springs':         { budget: [18, 30],  mid: [25, 45],   oem: [35, 65],   premium: [50, 90] },
  'suspension-arms':      { budget: [25, 45],  mid: [35, 65],   oem: [50, 95],   premium: [75, 140] },
  'tie-rod-ends':         { budget: [10, 18],  mid: [15, 28],   oem: [22, 40],   premium: [32, 55] },
  'wheel-bearings':       { budget: [20, 35],  mid: [30, 55],   oem: [45, 80],   premium: [65, 120] },
  'anti-roll-bar-links':  { budget: [8, 15],   mid: [12, 22],   oem: [18, 32],   premium: [25, 45] },
  'batteries':            { budget: [55, 75],  mid: [70, 95],   oem: [85, 120],  premium: [100, 160] },
  'alternators':          { budget: [80, 130], mid: [110, 180], oem: [150, 250], premium: [200, 350] },
  'starter-motors':       { budget: [70, 120], mid: [100, 170], oem: [140, 240], premium: [190, 320] },
  'bulbs':                { budget: [3, 6],    mid: [5, 10],    oem: [8, 15],    premium: [12, 25] },
  'sensors':              { budget: [12, 25],  mid: [20, 40],   oem: [30, 60],   premium: [45, 90] },
  'ignition-coils':       { budget: [15, 25],  mid: [22, 38],   oem: [30, 55],   premium: [45, 80] },
  'radiators':            { budget: [55, 90],  mid: [80, 140],  oem: [110, 200], premium: [160, 280] },
  'thermostats':          { budget: [8, 15],   mid: [12, 22],   oem: [18, 32],   premium: [25, 45] },
  'water-pumps':          { budget: [20, 35],  mid: [30, 55],   oem: [42, 75],   premium: [60, 110] },
  'heater-parts':         { budget: [25, 45],  mid: [35, 65],   oem: [50, 90],   premium: [70, 130] },
  'cooling-fans':         { budget: [35, 60],  mid: [50, 90],   oem: [70, 130],  premium: [100, 180] },
  'clutch-kits':          { budget: [65, 110], mid: [90, 160],  oem: [130, 230], premium: [180, 320] },
  'flywheels':            { budget: [120, 200], mid: [170, 280], oem: [230, 400], premium: [320, 550] },
  'cv-joints':            { budget: [15, 28],  mid: [22, 40],   oem: [32, 58],   premium: [45, 80] },
  'gearbox-mounts':       { budget: [18, 30],  mid: [25, 45],   oem: [35, 65],   premium: [50, 90] },
  'wiper-blades':         { budget: [6, 10],   mid: [8, 16],    oem: [12, 22],   premium: [18, 35] },
  'exhaust-parts':        { budget: [20, 45],  mid: [35, 70],   oem: [55, 110],  premium: [80, 160] },
  'wing-mirrors':         { budget: [25, 45],  mid: [35, 70],   oem: [55, 110],  premium: [80, 160] },
  'headlights':           { budget: [40, 75],  mid: [60, 120],  oem: [90, 180],  premium: [140, 280] },
};
